server.port=8080
# Sửa lại URL trỏ về PostgreSQL (Cổng 5432)
<<<<<<< Updated upstream
spring.datasource.url=jdbc:postgresql://localhost:5432/CafeWork

=======
>>>>>>> Stashed changes
# Tên đăng nhập và mật khẩu DB của bệ hạ (Hãy điền đúng mật khẩu của ngài)
spring.datasource.username=postgres
spring.datasource.password=admin

# Trả lại Driver và Dialect cho PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Tự động cập nhật cột (để tự tạo cột seat_status lúc nãy)
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/CafeWork?stringtype=unspecified