# Sửa lại URL trỏ về PostgreSQL (Cổng 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/cafework_db

# Tên đăng nhập và mật khẩu DB của bệ hạ (Hãy điền đúng mật khẩu của ngài)
spring.datasource.username=postgres
spring.datasource.password=123456

# Trả lại Driver và Dialect cho PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:postgresql://localhost:5432/cafework_db?stringtype=unspecified